

### Mode: GFuzz | Subdir: file(29)-test(1)-recovery_test-TestCustomRecoveryWithWriter ###

=== RUN   TestCustomRecoveryWithWriter
--- PASS: TestCustomRecoveryWithWriter (0.00s)
PASS
ok  	github.com/gin-gonic/gin	0.009s
FileName:  /home/ilian/Projects/Go_Fuzzing_Concurrency/Examples/Examples_Projects/gin-master/recovery_test.go
TestName:  TestCustomRecoveryWithWriter
Import added at line: 7
Header added at line: 163
Header added at file: /home/ilian/Projects/Go_Fuzzing_Concurrency/Examples/Examples_Projects/gin-master/recovery_test.go
go version go1.24.1 linux/amd64 ADVOCATE
=== RUN   TestCustomRecoveryWithWriter

Exit Replay with code  3 The program panicked unexpectedly
Exit Message: panic: Oupps, Houston, we have a problem

FAIL	github.com/gin-gonic/gin	0.109s
FAIL


### Mode: GFuzzHB | Subdir: file(29)-test(1)-recovery_test-TestCustomRecoveryWithWriter ###

=== RUN   TestCustomRecoveryWithWriter
--- PASS: TestCustomRecoveryWithWriter (0.00s)
PASS
ok  	github.com/gin-gonic/gin	0.008s
FileName:  /home/ilian/Projects/Go_Fuzzing_Concurrency/Examples/Examples_Projects/gin-master/recovery_test.go
TestName:  TestCustomRecoveryWithWriter
Import added at line: 7
Header added at line: 163
Header added at file: /home/ilian/Projects/Go_Fuzzing_Concurrency/Examples/Examples_Projects/gin-master/recovery_test.go
go version go1.24.1 linux/amd64 ADVOCATE
=== RUN   TestCustomRecoveryWithWriter

Exit Replay with code  3 The program panicked unexpectedly
Exit Message: panic: Oupps, Houston, we have a problem

FAIL	github.com/gin-gonic/gin	0.110s
FAIL
Bugreport info: 0_1,fail


### Mode: Flow | Subdir: file(29)-test(1)-recovery_test-TestCustomRecoveryWithWriter ###

=== RUN   TestCustomRecoveryWithWriter
--- PASS: TestCustomRecoveryWithWriter (0.00s)
PASS
ok  	github.com/gin-gonic/gin	0.007s
FileName:  /home/ilian/Projects/Go_Fuzzing_Concurrency/Examples/Examples_Projects/gin-master/recovery_test.go
TestName:  TestCustomRecoveryWithWriter
Import added at line: 7
Header added at line: 163
Header added at file: /home/ilian/Projects/Go_Fuzzing_Concurrency/Examples/Examples_Projects/gin-master/recovery_test.go
go version go1.24.1 linux/amd64 ADVOCATE
=== RUN   TestCustomRecoveryWithWriter

Exit Replay with code  3 The program panicked unexpectedly
Exit Message: panic: Oupps, Houston, we have a problem

FAIL	github.com/gin-gonic/gin	0.110s
FAIL
Bugreport info: 0_1,fail


### Mode: GFuzzHBFlow | Subdir: file(29)-test(1)-recovery_test-TestCustomRecoveryWithWriter ###

=== RUN   TestCustomRecoveryWithWriter
--- PASS: TestCustomRecoveryWithWriter (0.00s)
PASS
ok  	github.com/gin-gonic/gin	0.008s
FileName:  /home/ilian/Projects/Go_Fuzzing_Concurrency/Examples/Examples_Projects/gin-master/recovery_test.go
TestName:  TestCustomRecoveryWithWriter
Import added at line: 7
Header added at line: 163
Header added at file: /home/ilian/Projects/Go_Fuzzing_Concurrency/Examples/Examples_Projects/gin-master/recovery_test.go
go version go1.24.1 linux/amd64 ADVOCATE
=== RUN   TestCustomRecoveryWithWriter

Exit Replay with code  3 The program panicked unexpectedly
Exit Message: panic: Oupps, Houston, we have a problem

FAIL	github.com/gin-gonic/gin	0.109s
FAIL
Bugreport info: 0_1,fail


### Mode: GoPie | Subdir: file(29)-test(1)-recovery_test-TestCustomRecoveryWithWriter ###

=== RUN   TestCustomRecoveryWithWriter
--- PASS: TestCustomRecoveryWithWriter (0.00s)
PASS
ok  	github.com/gin-gonic/gin	0.008s
FileName:  /home/ilian/Projects/Go_Fuzzing_Concurrency/Examples/Examples_Projects/gin-master/recovery_test.go
TestName:  TestCustomRecoveryWithWriter
Import added at line: 7
Header added at line: 163
Header added at file: /home/ilian/Projects/Go_Fuzzing_Concurrency/Examples/Examples_Projects/gin-master/recovery_test.go
go version go1.24.1 linux/amd64 ADVOCATE
=== RUN   TestCustomRecoveryWithWriter

Exit Replay with code  3 The program panicked unexpectedly
Exit Message: panic: Oupps, Houston, we have a problem

FAIL	github.com/gin-gonic/gin	0.110s
FAIL


### Mode: GoPie+ | Subdir: file(29)-test(1)-recovery_test-TestCustomRecoveryWithWriter ###

=== RUN   TestCustomRecoveryWithWriter
--- PASS: TestCustomRecoveryWithWriter (0.00s)
PASS
ok  	github.com/gin-gonic/gin	0.008s
FileName:  /home/ilian/Projects/Go_Fuzzing_Concurrency/Examples/Examples_Projects/gin-master/recovery_test.go
TestName:  TestCustomRecoveryWithWriter
Import added at line: 7
Header added at line: 163
Header added at file: /home/ilian/Projects/Go_Fuzzing_Concurrency/Examples/Examples_Projects/gin-master/recovery_test.go
go version go1.24.1 linux/amd64 ADVOCATE
=== RUN   TestCustomRecoveryWithWriter

Exit Replay with code  3 The program panicked unexpectedly
Exit Message: panic: Oupps, Houston, we have a problem

FAIL	github.com/gin-gonic/gin	0.109s
FAIL


### Mode: GoPieHB | Subdir: file(29)-test(1)-recovery_test-TestCustomRecoveryWithWriter ###

=== RUN   TestCustomRecoveryWithWriter
--- PASS: TestCustomRecoveryWithWriter (0.00s)
PASS
ok  	github.com/gin-gonic/gin	0.008s
FileName:  /home/ilian/Projects/Go_Fuzzing_Concurrency/Examples/Examples_Projects/gin-master/recovery_test.go
TestName:  TestCustomRecoveryWithWriter
Import added at line: 7
Header added at line: 163
Header added at file: /home/ilian/Projects/Go_Fuzzing_Concurrency/Examples/Examples_Projects/gin-master/recovery_test.go
go version go1.24.1 linux/amd64 ADVOCATE
=== RUN   TestCustomRecoveryWithWriter

Exit Replay with code  3 The program panicked unexpectedly
Exit Message: panic: Oupps, Houston, we have a problem

FAIL	github.com/gin-gonic/gin	0.108s
FAIL
Bugreport info: 0_1,fail
